[versions]
kotlinVersion = "1.8.10"

[libraries]
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin ", version.ref="kotlinVersion"  }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test ", version.ref="kotlinVersion"  }

[plugins]
