[versions]
kotlinVersion = "1.8.10"
kotlinLanguageVersionsGradle = "1.8"
ktorVersion = "2.2.4"

[libraries]
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }

kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinVersion" }

ktorCore = { module = "io.ktor:ktor-server-core", version.ref = "ktorVersion" }
ktorNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktorVersion" }

[plugins]
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }

[bundles]
ktorServer = ["ktorCore", "ktorNetty"]
tests = ["kotlinTest"]