name: pull_request_checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronized
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository...
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build
        uses: ./gradlew build

      - name: Static analyze (all project)
        uses: ./gradlew detektProject

      - name: Run tests
        uses: ./gradlew test

      - name: Uploading analyze report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt.sarif
